version: '3.8'
services:
  configsvr:
    image: mongo:5.0
    container_name: configsvr
    command: ["mongod", "--configsvr", "--replSet", "configReplSet", "--port", "27017", "--dbpath", "/data/configdb"]
    volumes:
      - config_data:/data/configdb
    ports:
      - "27020:27017"

  shard1_mongo1:
    image: mongo:5.0
    container_name: shard1_mongo1
    command: ["mongod", "--shardsvr", "--replSet", "shard1ReplSet", "--port", "27017"]
    volumes:
      - shard1_mongo1_data:/data/db
    ports:
      - "27021:27017"

  shard1_mongo2:
    image: mongo:5.0
    container_name: shard1_mongo2
    command: ["mongod", "--shardsvr", "--replSet", "shard1ReplSet", "--port", "27017"]
    volumes:
      - shard1_mongo2_data:/data/db
    ports:
      - "27022:27017"

  shard1_arbiter:
    image: mongo:5.0
    container_name: shard1_arbiter
    command: ["mongod", "--shardsvr", "--replSet", "shard1ReplSet", "--port", "27017"]
    volumes:
      - shard1_arbiter_data:/data/db
    ports:
      - "27023:27017"

  shard2_mongo1:
    image: mongo:5.0
    container_name: shard2_mongo1
    command: ["mongod", "--shardsvr", "--replSet", "shard2ReplSet", "--port", "27017"]
    volumes:
      - shard2_mongo1_data:/data/db
    ports:
      - "27024:27017"

  shard2_mongo2:
    image: mongo:5.0
    container_name: shard2_mongo2
    command: ["mongod", "--shardsvr", "--replSet", "shard2ReplSet", "--port", "27017"]
    volumes:
      - shard2_mongo2_data:/data/db
    ports:
      - "27025:27017"

  shard2_arbiter:
    image: mongo:5.0
    container_name: shard2_arbiter
    command: ["mongod", "--shardsvr", "--replSet", "shard2ReplSet", "--port", "27017"]
    volumes:
      - shard2_arbiter_data:/data/db
    ports:
      - "27026:27017"

  mongos:
    image: mongo:5.0
    container_name: mongos
    command: ["mongos", "--configdb", "configReplSet/configsvr:27017", "--bind_ip_all"]
    ports:
      - "27027:27017"
    depends_on:
      - configsvr
      - shard1_mongo1
      - shard1_mongo2
      - shard2_mongo1
      - shard2_mongo2

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-demo-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongos:27017/mongoprojectdb2
    depends_on:
      - mongos

volumes:
  config_data:
  shard1_mongo1_data:
  shard1_mongo2_data:
  shard1_arbiter_data:
  shard2_mongo1_data:
  shard2_mongo2_data:
  shard2_arbiter_data: