version: '3.8'
services:
  mongodb1:
    image: mongo:5.0
    container_name: mongodb1
    ports:
      - "27017:27017"
    command: ["--replSet", "rs0"]
    #command: [ "/bin/bash", "-c", "mongod --replSet rs0 & sleep 5 && mongosh /scripts/init-replica.js" ]
    volumes:
      - mongo1_data:/data/db
      - ./init-replica.js:/scripts/init-replica.js
    environment:
      MONGO_INITDB_DATABASE: mongoprojectdb2

  mongodb2:
    image: mongo:5.0
    container_name: mongodb2
    restart: always
    ports:
      - "27018:27017"
    command: ["--replSet", "rs0"]
    volumes:
      - mongo2_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: mongoprojectdb2

  mongo-arbiter:
    image: mongo:5.0
    container_name: mongo-arbiter
    restart: always
    command: [ "--replSet", "rs0" ]
    ports:
      - "27019:27017"
    volumes:
      - mongo_arbiter_data:/data/db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-demo-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb1:27017,mongodb2:27017/mongoprojectdb2?replicaSet=rs0
    depends_on:
      - mongodb1

volumes:
  mongo1_data:
  mongo2_data:
  mongo_arbiter_data:


#command: [ "/bin/bash", "-c", "mongod --replSet rs0 & sleep 5 && mongosh /scripts/init-replica.js" ]